#! /usr/bin/python3.5

import time
import RPi.GPIO as GPIO

Led_1 = 18
Led_2 = 24
Led_3 = 21

GPIO.setmode(GPIO.BCM)
GPIO.setup(Led_1, GPIO.OUT)
GPIO.setup(Led_2, GPIO.OUT)
GPIO.setup(Led_3, GPIO.OUT)

def blink(el, time_delay=0.2):
	GPIO.output(el, True)
	time.sleep(time_delay)
	GPIO.output(el, False)
	time.sleep(time_delay)

Count = 0
while Count < 25:
	Count = Count + 1
	if Count % 3 == 0 and Count % 5 == 0:
		blink(Led_1, time_delay=0.05)
		blink(Led_2, time_delay=0.05)
		blink(Led_3, time_delay=0.05)
	if Count % 3 == 0:
		blink(Led_1, time_delay=0.4)
	elif Count % 5 == 0:
		blink(Led_2, time_delay=0.6)
	else:
		blink(Led_3)
	print(Count)
